/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_UsuarioLogin;
import Modelo.MetodosUsuario;
import sun.security.jgss.spi.MechanismFactory;
/**
 *
 * @author JorgeIgnacio
 */
public class FRM_UsuarioLogin extends javax.swing.JFrame {

    //Referencias
    Controlador_FRM_UsuarioLogin controlador_FRM_UsuarioLogin;
    MetodosUsuario metodosUsuario;
    
    public FRM_UsuarioLogin() {
        initComponents();
        controlador_FRM_UsuarioLogin = new Controlador_FRM_UsuarioLogin(this);
        this.gUI_LoginUsuario1.agregarEventos(controlador_FRM_UsuarioLogin);
    }
    
    public String[] devolverInfoLogin()
    {
        return this.gUI_LoginUsuario1.devolverInfoLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_LoginUsuario1 = new Vista.GUI_LoginUsuario();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_LoginUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_LoginUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_LoginUsuario gUI_LoginUsuario1;
    // End of variables declaration//GEN-END:variables
}
